docs/README.md

Fixes README.md
#trivial: No changelog because this won't be a release.

Fix readme

---

CHANGELOG.md
messages/en.json
messages/es.json
messages/pt.json
react/Installments.tsx
store/contentSchemas.json
store/interfaces.json

Add `product-installments`
[Workspace](https://productprice--storecomponents.myvtex.com/fashion-eyeglasses/p)
You can also edit this content through the site editor.

Add Installments

---

.vscode/settings.json
CHANGELOG.md
messages/en.json
messages/es.json
messages/pt.json
react/ListPrice.tsx
react/Savings.tsx
react/SellingPrice.tsx
store/contentSchemas.json
store/interfaces.json

Implementation of `SellingPrice`
[Workspace](https://productprice--storecomponents.myvtex.com/gorgeous-watch/p)
You can also edit this value on site-editor

Added `SellingPrice`

---

CHANGELOG.md
messages/en.json
messages/es.json
messages/pt.json

[Workspace](https://productprice--storecomponents.myvtex.com/tank-top/p)

Update default messages

---

CHANGELOG.md
react/Installments.tsx
react/Savings.tsx

[Workspace](https://productprice--storecomponents.myvtex.com/)
Check the savings' CSS handles

Fix handleBase

---

CHANGELOG.md
docs/README.md

[Workspace](https://productprice--storecomponents.myvtex.com/)

Improved README

---

CHANGELOG.md
docs/README.md

hotfix: fix the blocks' names

---

CHANGELOG.md
react/Installments.tsx
react/ListPrice.tsx
react/ListPriceRange.tsx
react/Savings.tsx
react/SellingPrice.tsx
react/SellingPriceRange.tsx

Fixes problems that were causing console warnings
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/tank-top/p)
Check that there are no errors related to this app on the console, while there is on [master](ttps://storecomponents.myvtex.com/tank-top/p)

Fixed errors causing warnings on console

---

CHANGELOG.md
react/Installments.tsx

Installments now render nothing if the product doesn't have installments.
[Workspace](https://phdro--kevinyee.myvtex.com/)
Check that there is not installment information here.

`Installments` now renders nothing if it is empty.

---

CHANGELOG.md
react/Installments.tsx

[Workspace](https://iaronaraujo--storecomponents.myvtex.com/gorgeous-watch/p)

Fix `undefined` check in `Installments`.

---

CHANGELOG.md
docs/README.md
messages/es.json
messages/pt.json
react/SellingPrice.tsx
react/package.json
react/typings/vtex.css-handles.d.ts
react/yarn.lock
yarn.lock

https://sellinglist--storecomponents.myvtex.com/
You should see a difference in the `sellingPrice` when there is a `listPrice`

Apply modifier to sellingPrice handle if there is a listPrice

---

CHANGELOG.md
docs/README.md
messages/en.json
messages/es.json
messages/pt.json
react/SpotPrice.tsx
react/yarn.lock
store/contentSchemas.json
store/interfaces.json

[Workspace](https://productprice--storecomponents.myvtex.com/fashion-eyeglasses/p)
Needs https://github.com/vtex-apps/store-resources/pull/113

Add `product-spot-price`

---

CHANGELOG.md
react/Installments.tsx
react/ListPrice.tsx
react/ListPriceRange.tsx
react/Savings.tsx
react/SellingPrice.tsx
react/SellingPriceRange.tsx
react/SpotPrice.tsx

[Workspace](https://iaronaraujo--storecomponents.myvtex.com/gorgeous-watch/p)

Fixed missing defaults on `defineMessages`

---

CHANGELOG.md
react/ListPrice.tsx
react/ListPriceRange.tsx
react/Savings.tsx
react/SellingPrice.tsx
react/SellingPriceRange.tsx
react/SpotPrice.tsx

Fixes `selling-price` and `selling-price-range` showing price 0 when there were no available products.
[Workspace](https://testv050--bestbrand.myvtex.com/traje-executive-azul-550/p?skuId=1859)

Fixed price 0 on unavailable products

---

CHANGELOG.md
docs/README.md

Making clear how to add default message prop on the product-price blocks
Put message prop to each block.
Related to Issue #32

Adding message prop usage and example on documentation

---

CHANGELOG.md
manifest.json
react/Installments.tsx
react/InstallmentsList.tsx
react/InstallmentsListItem.tsx
react/ListPrice.tsx
react/ListPriceRange.tsx
react/PriceSuspense.tsx
react/Savings.tsx
react/SellerName.tsx
react/SellingPrice.tsx
react/SellingPriceRange.tsx
react/SpotPrice.tsx
react/SpotPriceSavings.tsx
react/components/InstallmentsRenderer.tsx
react/components/PriceLoadingSpinner/index.tsx
react/package.json
react/yarn.lock

Add support for custom classes via css-handles@1.x
https://breact--storecomponents.myvtex.com/

Feature css

---

CHANGELOG.md
docs/README.md
react/ListPrice.tsx
react/SellingPrice.tsx

Avoid breaking current stores expectations.
Before:
https://brenovtex--arcaplanet.myvtex.com/in-the-nature-cat-vasch-gr-85-prosciutto/p
After:
https://brenovtex2--arcaplanet.myvtex.com/in-the-nature-cat-vasch-gr-85-prosciutto/p
https://breno--storecomponents.myvtex.com/orange-juice/p
The ones before

Create new variable sellingPriceWithUnitMultiplier in product-selling-price

---

CHANGELOG.md
docs/README.md

Make it easier for other developers to know how to use unitMultiplier and measurementUnit variables.
https://breno--storecomponents.myvtex.com/orange-juice/p

Add example of usage of unit multiplier and measurement unit

---

CHANGELOG.md
docs/README.md
react/Installments.tsx
react/InstallmentsListItem.tsx
react/components/InstallmentsRenderer.tsx
react/modules/slug.ts
react/package.json
react/yarn.lock

This is a way to provide further customization options to our users.
Take a look at this [Workspace](https://productprice--storecomponents.myvtex.com/everyday-necessaire/p).
Directly related to a Jira issue: https://vtex-dev.atlassian.net/browse/IOSF-329

Add CSS handles modifiers to 'paymentSystemName' and 'installmentsNumber'

---

CHANGELOG.md
docs/README.md
react/Installments.tsx
react/__mocks__/installments-list-mock.ts
react/__tests__/pickInstallments.test.ts
react/modules/pickInstallments.ts

Our current `product-installments` block doesn't offer much when it comes to customization. We would always render information regarding the installments option with the most installments (max value for `installment.NumberOfInstallments`).
This PR should allow our users to have greater control over which installments plan they want to show their customers.
In this [Workspace](https://productprice--storecomponents.myvtex.com/tank-top/p), I had this branch linked using the following configuration:
```json
{
"product-installments": {
"props": {
"installmentsCriteria": "max-quantity-without-interest",
"installmentOptionsFilter": {
"paymentSystemName": "Customer Credit"
}
}
}
}
```
Here are a few options available as installment plans for the product you're seeing:
Notice that there's an …

Add new props 'installmentsCriteria' and 'installmentOptionsFilter' to 'product-installments' block
